### ISSUE TITLE
error while running main.py

### ISSUE THREAD

**Issue by MogaliLokesh** [MontrealTradingGroup/freqtrade#13]
2022-02-26 03:13:13,123 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "./freqtrade/main.py", line 49, in main
    state = freqtrade.worker(old_state=state)
  File "/home/mtg/freqtrade/freqtrade/freqtradebot.py", line 122, in worker
    min_secs=min_secs)
  File "/home/mtg/freqtrade/freqtrade/freqtradebot.py", line 134, in _throttle
    result = func(*args, **kwargs)
  File "/home/mtg/freqtrade/freqtrade/freqtradebot.py", line 170, in _process
    self.exchange.refresh_tickers(self.active_pair_whitelist, self.strategy.ticker_interval)
  File "/home/mtg/freqtrade/freqtrade/exchange/__init__.py", line 536, in refresh_tickers
    self.async_get_candles_history(pair_list, ticker_interval))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/mtg/freqtrade/freqtrade/exchange/__init__.py", line 548, in async_get_candles_history
    arrow.utcnow().timestamp and pair in self._klines):
TypeError: '>=' not supported between instances of 'int' and 'method'

can anyone suggest how to resolve this error

**Comment by onahMo** [comment]
**got the same error**

![Screenshot from 2022-03-19 04-30-52](https://user-images.githubusercontent.com/69719587/159103452-773f42a2-f19f-4d04-8c3e-914a182c3f8b.png)
