### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by MrN8** [MontrealTradingGroup/freqtrade#5]
// paste your log here
  ```
hi sorry the bot gives me an error
Error : Traceback (most recent call last):
File "./freqtrade/main.py", line 11, in
from freqtrade import OperationalException
ModuleNotFoundError: No module named 'freqtrade'

**Comment by OtenMoten** [comment]
Hello dear MTG team and MrN8,

I got the same error:

mtg@mtgvb:~/freqtrade$ python3.6 ./scripts/plot_dataframe.py -s BBRSI -p LINK/BTC

/home/mtg/.local/lib/python3.6/site-packages/jupyter_client/session.py:56: 
VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  from zmq.eventloop.ioloop import IOLoop
Traceback (most recent call last):
  File "./scripts/plot_dataframe.py", line 41, in <module>
    from freqtrade import persistence
ModuleNotFoundError: No module named 'freqtrade'

**Comment by OtenMoten** [comment]
Hello Sir,

use [this workaround](https://github.com/MontrealTradingGroup/freqtrade/issues/6).

EDIT:

Are there any errors left @MrN8 ?
